//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DVTEntities : DbContext
    {
        public DVTEntities()
            : base("name=DVTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressDetail> AddressDetail { get; set; }
        public virtual DbSet<Addresss> Addresss { get; set; }
        public virtual DbSet<AddressType> AddressType { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Delegate> Delegate { get; set; }
        public virtual DbSet<Dietary> Dietary { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Training> Training { get; set; }
        public virtual DbSet<TrainingPayment> TrainingPayment { get; set; }
    }
}
